# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rafael\Desktop\PROJETINHO\LOGIN\telaconversao.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(535, 459)
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(101, 252, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labeltext0 = QtWidgets.QLabel(self.centralwidget)
        self.labeltext0.setGeometry(QtCore.QRect(140, 10, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        self.labeltext0.setFont(font)
        self.labeltext0.setStyleSheet("background-color: rbg(255, 255, 255);\n"
"border-radius: 15px; \n"
"border-style: outset; \n"
"border-width: 2px;")
        self.labeltext0.setLineWidth(15)
        self.labeltext0.setMidLineWidth(15)
        self.labeltext0.setTextFormat(QtCore.Qt.MarkdownText)
        self.labeltext0.setIndent(7)
        self.labeltext0.setOpenExternalLinks(False)
        self.labeltext0.setObjectName("labeltext0")
        self.powerlabel = QtWidgets.QLabel(self.centralwidget)
        self.powerlabel.setGeometry(QtCore.QRect(10, 430, 131, 16))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        self.powerlabel.setFont(font)
        self.powerlabel.setObjectName("powerlabel")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 420, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: rgb(250, 216, 255);\n"
"border-radius: 15px; \n"
"border-style: outset; \n"
"border-width: 2px;\n"
"border-color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(250, 216, 255);\n"
"border-style: outset; \n"
"border-width: 2px;\n"
"border-radius: 15px; \n"
"border-color: white;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 140, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(250, 216, 255);\n"
"border-style: outset; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-width: 2px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 220, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(250, 216, 255);\n"
"border-style: outset; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-width: 2px;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 140, 251, 41))
        self.lineEdit.setStyleSheet("background-color: rbg(255, 255, 255);\n"
"border-radius: 15px; \n"
"border-style: outset; \n"
"border-width: 2px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 220, 251, 41))
        self.lineEdit_2.setStyleSheet("background-color: rbg(255, 255, 255);\n"
"border-radius: 15px; \n"
"border-style: outset; \n"
"border-width: 2px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 280, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background-color: rgb(250, 216, 255);\n"
"border-radius: 15px; \n"
"border-style: outset; \n"
"border-width: 2px;\n"
"border-color: black;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(250, 216, 255);\n"
"border-style: outset; \n"
"border-width: 2px;\n"
"border-radius: 15px; \n"
"border-color: white;\n"
"\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela principal"))
        self.labeltext0.setText(_translate("MainWindow", "WEATHER FORECAST"))
        self.powerlabel.setText(_translate("MainWindow", "POWERED BY: RAFAEL"))
        self.pushButton_2.setText(_translate("MainWindow", "SAIR"))
        self.comboBox.setItemText(0, _translate("MainWindow", "CELSIUS"))
        self.comboBox.setItemText(1, _translate("MainWindow", "FAHRENHEIT"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "FAHRENHEIT"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "CELSIUS"))
        self.pushButton_3.setText(_translate("MainWindow", "CONFIRMAR"))
